In [2]:
import pandas as pd
import numpy as np

coin_name = "KRW-XRP"
df = pd.read_csv('./data/{}.csv'.format(coin_name))
df = df.sort_values(by='timestamp', ascending=True)
columns={'timestamp':'t', 'openingPrice':'o', 'highPrice':'h', 'lowPrice':'l', 'tradePrice':'c', 'candleAccTradeVolume':'v'}
df = df.rename(columns=columns)
df.shape

(200000, 7)

In [2]:
##### 단순 이동평균 계산

from ta.trend import SMAIndicator
df['sma7'] = SMAIndicator(df['c'], window=7).sma_indicator()
df['sma14'] = SMAIndicator(df['c'], window=25).sma_indicator()
df['sma99'] = SMAIndicator(df['c'], window=99).sma_indicator()
df.head(10)

,t,o,h,l,c,v,sma7,sma14,sma99
199999,2021-03-31 23:47:00.044,692,693,691,692,218126.023628,NaN,NaN,NaN
199998,2021-03-31 23:47:59.899,691,692,690,691,802408.558260,NaN,NaN,NaN
199997,2021-03-31 23:49:00.171,691,692,690,690,175645.592917,NaN,NaN,NaN
199996,2021-03-31 23:50:00.405,691,692,691,691,537361.021905,NaN,NaN,NaN
199995,2021-03-31 23:50:58.652,691,692,690,691,493475.979903,NaN,NaN,NaN
199994,2021-03-31 23:51:59.659,692,693,691,693,478325.511369,NaN,NaN,NaN
199993,2021-03-31 23:52:59.484,692,693,691,691,375022.709017,691.285714,NaN,NaN
199992,2021-03-31 23:53:59.967,691,692,691,692,468191.386241,691.285714,NaN,NaN
199991,2021-03-31 23:55:00.036,692,693,691,692,767081.074961,691.428571,NaN,NaN
199990,2021-03-31 23:55:59.682,693,693,692,693,353523.292541,691.857143,NaN,NaN

In [3]:
##### 가중 이동평균 계산

from ta.trend import WMAIndicator
df['wma7'] = WMAIndicator(df['c'], window=7).wma()
df['wma25'] = WMAIndicator(df['c'], window=25).wma()
df['wma99'] = WMAIndicator(df['c'], window=99).wma()
df.head(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,wma25,wma99
199999,2021-03-31 23:47:00.044,692,693,691,692,218126.023628,NaN,NaN,NaN,NaN,NaN,NaN
199998,2021-03-31 23:47:59.899,691,692,690,691,802408.558260,NaN,NaN,NaN,NaN,NaN,NaN
199997,2021-03-31 23:49:00.171,691,692,690,690,175645.592917,NaN,NaN,NaN,NaN,NaN,NaN
199996,2021-03-31 23:50:00.405,691,692,691,691,537361.021905,NaN,NaN,NaN,NaN,NaN,NaN
199995,2021-03-31 23:50:58.652,691,692,690,691,493475.979903,NaN,NaN,NaN,NaN,NaN,NaN
199994,2021-03-31 23:51:59.659,692,693,691,693,478325.511369,NaN,NaN,NaN,NaN,NaN,NaN
199993,2021-03-31 23:52:59.484,692,693,691,691,375022.709017,691.285714,NaN,NaN,691.357143,NaN,NaN
199992,2021-03-31 23:53:59.967,691,692,691,692,468191.386241,691.285714,NaN,NaN,691.535714,NaN,NaN
199991,2021-03-31 23:55:00.036,692,693,691,692,767081.074961,691.428571,NaN,NaN,691.714286,NaN,NaN
199990,2021-03-31 23:55:59.682,693,693,692,693,353523.292541,691.857143,NaN,NaN,692.107143,NaN,NaN

In [4]:
##### 지수 이동평균 계산

from ta.trend import EMAIndicator
df['ema7'] = EMAIndicator(df['c'], window=7).ema_indicator()
df['ema25'] = EMAIndicator(df['c'], window=25).ema_indicator()
df['ema99'] = EMAIndicator(df['c'], window=99).ema_indicator()
df.head(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,wma25,wma99,ema7,ema25,ema99
199999,2021-03-31 23:47:00.044,692,693,691,692,218126.023628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998,2021-03-31 23:47:59.899,691,692,690,691,802408.558260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199997,2021-03-31 23:49:00.171,691,692,690,690,175645.592917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199996,2021-03-31 23:50:00.405,691,692,691,691,537361.021905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199995,2021-03-31 23:50:58.652,691,692,690,691,493475.979903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199994,2021-03-31 23:51:59.659,692,693,691,693,478325.511369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199993,2021-03-31 23:52:59.484,692,693,691,691,375022.709017,691.285714,NaN,NaN,691.357143,NaN,NaN,691.473877,NaN,NaN
199992,2021-03-31 23:53:59.967,691,692,691,692,468191.386241,691.285714,NaN,NaN,691.535714,NaN,NaN,691.605408,NaN,NaN
199991,2021-03-31 23:55:00.036,692,693,691,692,767081.074961,691.428571,NaN,NaN,691.714286,NaN,NaN,691.704056,NaN,NaN
199990,2021-03-31 23:55:59.682,693,693,692,693,353523.292541,691.857143,NaN,NaN,692.107143,NaN,NaN,692.028042,NaN,NaN

In [5]:
##### MACD 계산

from ta.trend import MACD
macd = MACD(df['c'], window_slow=26, window_fast=12, window_sign=9)
df['macd'] = macd.macd()
df['macd_s'] = macd.macd_signal()
df['macd_d'] = macd.macd_diff()
df.tail(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,wma25,wma99,ema7,ema25,ema99,macd,macd_s,macd_d
9,2021-08-17 23:50:59.612,1295,1300,1290,1290,1.648057e+06,1297.142857,1307.0,1315.101010,1295.892857,1303.800000,1313.570707,1296.897851,1304.788538,1315.926941,-5.143303,-3.826334,-1.316969
8,2021-08-17 23:52:00.395,1295,1295,1285,1285,1.972714e+06,1295.000000,1306.2,1314.848485,1292.857143,1302.107692,1312.968687,1293.923388,1303.266342,1315.308402,-5.952929,-4.251653,-1.701276
7,2021-08-17 23:52:59.999,1285,1295,1280,1285,3.075655e+06,1293.571429,1305.4,1314.646465,1290.357143,1300.476923,1312.371717,1291.692541,1301.861239,1314.702234,-6.519411,-4.705205,-1.814206
6,2021-08-17 23:53:59.494,1285,1290,1280,1280,1.759737e+06,1290.000000,1304.2,1314.393939,1286.964286,1298.523077,1311.678788,1288.769406,1300.179605,1314.008190,-7.287801,-5.221724,-2.066077
5,2021-08-17 23:54:59.882,1280,1295,1280,1285,1.736565e+06,1288.571429,1303.4,1314.040404,1285.714286,1297.046154,1311.090909,1287.827054,1299.011943,1313.428026,-7.407904,-5.658960,-1.748944
4,2021-08-17 23:56:00.273,1285,1290,1285,1285,9.446324e+05,1286.428571,1302.4,1313.737374,1284.821429,1295.630769,1310.510101,1287.120291,1297.934102,1312.859465,-7.417581,-6.010684,-1.406897
3,2021-08-17 23:56:59.848,1290,1295,1285,1290,1.232869e+06,1285.714286,1301.2,1313.434343,1285.714286,1294.676923,1310.035354,1287.840218,1297.323786,1312.402276,-6.941772,-6.196902,-0.744870
2,2021-08-17 23:58:00.128,1290,1295,1290,1295,1.759855e+06,1286.428571,1300.2,1313.282828,1288.035714,1294.200000,1309.666667,1289.630164,1297.145033,1312.054231,-6.091018,-6.175725,0.084707
1,2021-08-17 23:58:59.760,1290,1300,1290,1295,1.125005e+06,1287.857143,1299.2,1313.080808,1290.178571,1293.800000,1309.301010,1290.972623,1296.980031,1311.713146,-5.355059,-6.011592,0.656533
0,2021-08-18 00:00:00.224,1295,1300,1290,1300,5.783027e+05,1290.000000,1298.6,1312.979798,1293.214286,1293.861538,1309.039394,1293.229467,1297.212336,1311.478883,-4.318567,-5.672987,1.354420

In [6]:
##### RSI 계산
from ta.momentum import RSIIndicator
df['rsi7'] = RSIIndicator(df['c'], window=7).rsi()
df['rsi14'] = RSIIndicator(df['c'], window=14).rsi()
df['rsi28'] = RSIIndicator(df['c'], window=28).rsi()
df.head(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,...,wma99,ema7,ema25,ema99,macd,macd_s,macd_d,rsi7,rsi14,rsi28
199999,2021-03-31 23:47:00.044,692,693,691,692,218126.023628,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199998,2021-03-31 23:47:59.899,691,692,690,691,802408.558260,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199997,2021-03-31 23:49:00.171,691,692,690,690,175645.592917,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199996,2021-03-31 23:50:00.405,691,692,691,691,537361.021905,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199995,2021-03-31 23:50:58.652,691,692,690,691,493475.979903,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199994,2021-03-31 23:51:59.659,692,693,691,693,478325.511369,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199993,2021-03-31 23:52:59.484,692,693,691,691,375022.709017,691.285714,NaN,NaN,691.357143,...,NaN,691.473877,NaN,NaN,NaN,NaN,NaN,43.842507,NaN,NaN
199992,2021-03-31 23:53:59.967,691,692,691,692,468191.386241,691.285714,NaN,NaN,691.535714,...,NaN,691.605408,NaN,NaN,NaN,NaN,NaN,53.901738,NaN,NaN
199991,2021-03-31 23:55:00.036,692,693,691,692,767081.074961,691.428571,NaN,NaN,691.714286,...,NaN,691.704056,NaN,NaN,NaN,NaN,NaN,53.901738,NaN,NaN
199990,2021-03-31 23:55:59.682,693,693,692,693,353523.292541,691.857143,NaN,NaN,692.107143,...,NaN,692.028042,NaN,NaN,NaN,NaN,NaN,62.937845,NaN,NaN

In [7]:
##### StochRSI 계산
from ta.momentum import StochRSIIndicator
stochRSI = StochRSIIndicator(df['c'], window=14, smooth1=3, smooth2=3)
df['srsi'] = stochRSI.stochrsi()
df['srsik'] = stochRSI.stochrsi_k()
df['srsid'] = stochRSI.stochrsi_d()
df.tail(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,...,ema99,macd,macd_s,macd_d,rsi7,rsi14,rsi28,srsi,srsik,srsid
9,2021-08-17 23:50:59.612,1295,1300,1290,1290,1.648057e+06,1297.142857,1307.0,1315.101010,1295.892857,...,1315.926941,-5.143303,-3.826334,-1.316969,31.940812,35.762693,39.683943,0.225683,0.328549,0.356730
8,2021-08-17 23:52:00.395,1295,1295,1285,1285,1.972714e+06,1295.000000,1306.2,1314.848485,1292.857143,...,1315.308402,-5.952929,-4.251653,-1.701276,27.223974,32.725332,37.796432,0.066615,0.199211,0.286198
7,2021-08-17 23:52:59.999,1285,1295,1280,1285,3.075655e+06,1293.571429,1305.4,1314.646465,1290.357143,...,1314.702234,-6.519411,-4.705205,-1.814206,27.223974,32.725332,37.796432,0.089991,0.127429,0.218396
6,2021-08-17 23:53:59.494,1285,1290,1280,1280,1.759737e+06,1290.000000,1304.2,1314.393939,1286.964286,...,1314.008190,-7.287801,-5.221724,-2.066077,22.667733,29.790930,35.957149,0.000000,0.052202,0.126281
5,2021-08-17 23:54:59.882,1280,1295,1280,1285,1.736565e+06,1288.571429,1303.4,1314.040404,1285.714286,...,1313.428026,-7.407904,-5.658960,-1.748944,35.300606,35.973642,39.033819,0.391383,0.160458,0.113363
4,2021-08-17 23:56:00.273,1285,1290,1285,1285,9.446324e+05,1286.428571,1302.4,1313.737374,1284.821429,...,1312.859465,-7.417581,-6.010684,-1.406897,35.300606,35.973642,39.033819,0.391383,0.260922,0.157860
3,2021-08-17 23:56:59.848,1290,1295,1285,1290,1.232869e+06,1285.714286,1301.2,1313.434343,1285.714286,...,1312.402276,-6.941772,-6.196902,-0.744870,47.069618,41.906733,42.028912,0.766963,0.516576,0.312652
2,2021-08-17 23:58:00.128,1290,1295,1290,1295,1.759855e+06,1286.428571,1300.2,1313.282828,1288.035714,...,1312.054231,-6.091018,-6.175725,0.084707,56.335998,47.178073,44.839171,1.000000,0.719449,0.498982
1,2021-08-17 23:58:59.760,1290,1300,1290,1295,1.125005e+06,1287.857143,1299.2,1313.080808,1290.178571,...,1311.713146,-5.355059,-6.011592,0.656533,56.335998,47.178073,44.839171,1.000000,0.922321,0.719449
0,2021-08-18 00:00:00.224,1295,1300,1290,1300,5.783027e+05,1290.000000,1298.6,1312.979798,1293.214286,...,1311.478883,-4.318567,-5.672987,1.354420,64.738357,52.207562,47.572445,1.000000,1.000000,0.880590

In [8]:
##### Bollinger Bands 계산

from ta.volatility import BollingerBands
bb = BollingerBands(df['c'], window=20, window_dev=2)
df['bh'] = bb.bollinger_hband() #high band
df['bhi'] = bb.bollinger_hband_indicator() #high band 보다 가격이 높으면 1, 아니면 0
df['bl'] = bb.bollinger_lband() #low band
df['bli'] = bb.bollinger_lband_indicator() #low band 보다 가격이 낮으면 1, 아니면 0
df['bm'] = bb.bollinger_mavg() #middle band
df['bw'] = bb.bollinger_wband() #band width
df.tail(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,...,rsi28,srsi,srsik,srsid,bh,bhi,bl,bli,bm,bw
9,2021-08-17 23:50:59.612,1295,1300,1290,1290,1.648057e+06,1297.142857,1307.0,1315.101010,1295.892857,...,39.683943,0.225683,0.328549,0.356730,1326.339080,0.0,1287.660920,0.0,1307.00,2.959308
8,2021-08-17 23:52:00.395,1295,1295,1285,1285,1.972714e+06,1295.000000,1306.2,1314.848485,1292.857143,...,37.796432,0.066615,0.199211,0.286198,1325.859464,0.0,1284.640536,0.0,1305.25,3.157934
7,2021-08-17 23:52:59.999,1285,1295,1280,1285,3.075655e+06,1293.571429,1305.4,1314.646465,1290.357143,...,37.796432,0.089991,0.127429,0.218396,1324.736761,0.0,1282.263239,0.0,1303.50,3.258421
6,2021-08-17 23:53:59.494,1285,1290,1280,1280,1.759737e+06,1290.000000,1304.2,1314.393939,1286.964286,...,35.957149,0.000000,0.052202,0.126281,1323.658520,0.0,1279.341480,0.0,1301.50,3.405074
5,2021-08-17 23:54:59.882,1280,1295,1280,1285,1.736565e+06,1288.571429,1303.4,1314.040404,1285.714286,...,39.033819,0.391383,0.160458,0.113363,1322.360680,0.0,1277.639320,0.0,1300.00,3.440105
4,2021-08-17 23:56:00.273,1285,1290,1285,1285,9.446324e+05,1286.428571,1302.4,1313.737374,1284.821429,...,39.033819,0.391383,0.260922,0.157860,1320.658520,0.0,1276.341480,0.0,1298.50,3.412941
3,2021-08-17 23:56:59.848,1290,1295,1285,1290,1.232869e+06,1285.714286,1301.2,1313.434343,1285.714286,...,42.028912,0.766963,0.516576,0.312652,1317.099751,0.0,1276.900249,0.0,1297.00,3.099422
2,2021-08-17 23:58:00.128,1290,1295,1290,1295,1.759855e+06,1286.428571,1300.2,1313.282828,1288.035714,...,44.839171,1.000000,0.719449,0.498982,1314.330303,0.0,1277.669697,0.0,1296.00,2.828750
1,2021-08-17 23:58:59.760,1290,1300,1290,1295,1.125005e+06,1287.857143,1299.2,1313.080808,1290.178571,...,44.839171,1.000000,0.922321,0.719449,1311.124515,0.0,1278.875485,0.0,1295.00,2.490273
0,2021-08-18 00:00:00.224,1295,1300,1290,1300,5.783027e+05,1290.000000,1298.6,1312.979798,1293.214286,...,47.572445,1.000000,1.000000,0.880590,1309.298649,0.0,1279.701351,0.0,1294.50,2.286388

In [9]:
##### VWAP 계산
from ta.volume import VolumeWeightedAveragePrice
vwap = VolumeWeightedAveragePrice(high=df['h'], low=df['l'], close=df['c'], volume=df['v'], window=14)
df['vwap'] = vwap.volume_weighted_average_price()
df.tail(10)

,t,o,h,l,c,v,sma7,sma14,sma99,wma7,...,srsi,srsik,srsid,bh,bhi,bl,bli,bm,bw,vwap
9,2021-08-17 23:50:59.612,1295,1300,1290,1290,1.648057e+06,1297.142857,1307.0,1315.101010,1295.892857,...,0.225683,0.328549,0.356730,1326.339080,0.0,1287.660920,0.0,1307.00,2.959308,1301.508016
8,2021-08-17 23:52:00.395,1295,1295,1285,1285,1.972714e+06,1295.000000,1306.2,1314.848485,1292.857143,...,0.066615,0.199211,0.286198,1325.859464,0.0,1284.640536,0.0,1305.25,3.157934,1299.016146
7,2021-08-17 23:52:59.999,1285,1295,1280,1285,3.075655e+06,1293.571429,1305.4,1314.646465,1290.357143,...,0.089991,0.127429,0.218396,1324.736761,0.0,1282.263239,0.0,1303.50,3.258421,1296.194418
6,2021-08-17 23:53:59.494,1285,1290,1280,1280,1.759737e+06,1290.000000,1304.2,1314.393939,1286.964286,...,0.000000,0.052202,0.126281,1323.658520,0.0,1279.341480,0.0,1301.50,3.405074,1294.297215
5,2021-08-17 23:54:59.882,1280,1295,1280,1285,1.736565e+06,1288.571429,1303.4,1314.040404,1285.714286,...,0.391383,0.160458,0.113363,1322.360680,0.0,1277.639320,0.0,1300.00,3.440105,1293.102130
4,2021-08-17 23:56:00.273,1285,1290,1285,1285,9.446324e+05,1286.428571,1302.4,1313.737374,1284.821429,...,0.391383,0.260922,0.157860,1320.658520,0.0,1276.341480,0.0,1298.50,3.412941,1292.381870
3,2021-08-17 23:56:59.848,1290,1295,1285,1290,1.232869e+06,1285.714286,1301.2,1313.434343,1285.714286,...,0.766963,0.516576,0.312652,1317.099751,0.0,1276.900249,0.0,1297.00,3.099422,1291.919386
2,2021-08-17 23:58:00.128,1290,1295,1290,1295,1.759855e+06,1286.428571,1300.2,1313.282828,1288.035714,...,1.000000,0.719449,0.498982,1314.330303,0.0,1277.669697,0.0,1296.00,2.828750,1291.605254
1,2021-08-17 23:58:59.760,1290,1300,1290,1295,1.125005e+06,1287.857143,1299.2,1313.080808,1290.178571,...,1.000000,0.922321,0.719449,1311.124515,0.0,1278.875485,0.0,1295.00,2.490273,1291.473005
0,2021-08-18 00:00:00.224,1295,1300,1290,1300,5.783027e+05,1290.000000,1298.6,1312.979798,1293.214286,...,1.000000,1.000000,0.880590,1309.298649,0.0,1279.701351,0.0,1294.50,2.286388,1291.474535

In [10]:
df = df.dropna()
df.columns

Index(['t', 'o', 'h', 'l', 'c', 'v', 'sma7', 'sma14', 'sma99', 'wma7', 'wma25',
       'wma99', 'ema7', 'ema25', 'ema99', 'macd', 'macd_s', 'macd_d', 'rsi7',
       'rsi14', 'rsi28', 'srsi', 'srsik', 'srsid', 'bh', 'bhi', 'bl', 'bli',
       'bm', 'bw', 'vwap'],
      dtype='object')

In [11]:
df.to_csv('./data/{}.csv'.format(coin_name))